steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/tynmarket-195002/github-tynmarket-coffeehub-baase', '-f', 'docker/Dockerfile-base', '.']
images: ['gcr.io/tynmarket-195002/github-tynmarket-coffeehub-base']
